#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ha_user WITH PASSWORD '$HA_USER_PASSWORD';
	CREATE DATABASE ha_db;
	GRANT ALL PRIVILEGES ON DATABASE ha_db TO ha_user;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "ha_db" <<-EOSQL
	GRANT ALL ON SCHEMA public TO ha_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ha_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ha_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ha_user;
EOSQL