#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER n8n_user WITH PASSWORD '$N8N_USER_PASSWORD';
	CREATE DATABASE n8n_db OWNER n8n_user;
	GRANT ALL PRIVILEGES ON DATABASE n8n_db TO n8n_user;
	GRANT CONNECT ON DATABASE n8n_db TO n8n_user;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "n8n_db" <<-EOSQL
	GRANT USAGE ON SCHEMA public TO n8n_user;
	GRANT ALL ON SCHEMA public TO n8n_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO n8n_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO n8n_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO n8n_user;
EOSQL